export const questions = [
  // Manatees - Passage 1
  {
    q: "Appearance: Manatees look similar to dugongs, but with a differently shaped (1) __________",
    options: ["tail"],
    correct: 0,
    explanation: "The passage states that while they look alike, the manatee has a broad, rounded tail, whereas the dugong's is fluked like a whale.",
  },
  {
    q: "Movement: Manatees need to use their (2) __________ to turn their bodies around in order to look sideways.",
    options: ["flippers"],
    correct: 0,
    explanation: "Because their short neck only allows up and down movement, they must turn their entire body steering with their flippers to see left or right.",
  },
  {
    q: "Movement: Manatees sense vibrations in the water by means of (3) __________ on their skin.",
    options: ["hairs"],
    correct: 0,
    explanation: "The text mentions that hairs covering their bodies help them sense vibrations in the water around them.",
  },
  {
    q: "Feeding: Manatees eat mainly aquatic vegetation, such as (4) __________",
    options: ["seagrasses"],
    correct: 0,
    explanation: "The passage notes that seagrasses and other marine plants make up most of a manatee's diet.",
  },
  {
    q: "Feeding: Manatees grasp and pull up plants with their (5) __________",
    options: ["lips"],
    correct: 0,
    explanation: "Instead of incisors, manatees have lips which function like a pair of hands to help tear food away from the seafloor.",
  },
  {
    q: "Breathing: Manatees may regulate the (6) __________ of their bodies by using muscles of the diaphragm to store air internally.",
    options: ["buoyancy"],
    correct: 0,
    explanation: "The text suggests manatees use their muscular diaphragm and breathing to adjust their buoyancy.",
  },
  {
    q: "West Indian manatees can be found in a variety of different aquatic habitats.",
    options: ["TRUE", "FALSE", "NOT GIVEN"],
    correct: 0,
    explanation: "The text states they move between fresh and salt water, including mangroves, coral reefs, rivers, lakes, and lagoons.",
  },
  {
    q: "The Florida manatee lives in warmer waters than the Antillean manatee.",
    options: ["TRUE", "FALSE", "NOT GIVEN"],
    correct: 2,
    explanation: "While the text mentions the locations and seasonal movements of both, it does not compare the water temperatures of their respective habitats.",
  },
  {
    q: "The African manatee's range is limited to coastal waters between the West African countries of Mauritania and Angola.",
    options: ["TRUE", "FALSE", "NOT GIVEN"],
    correct: 1,
    explanation: "The passage mentions that the African manatee also makes use of rivers in landlocked countries such as Mali and Niger.",
  },
  {
    q: "The extent of the loss of Amazonian manatees in the mid-twentieth century was only revealed many years later.",
    options: ["TRUE", "FALSE", "NOT GIVEN"],
    correct: 2,
    explanation: "The passage provides the estimated number of manatees killed between 1935 and 1954, but does not state when this information was revealed.",
  },
  {
    q: "It is predicted that West Indian manatee populations will fall in the coming decades.",
    options: ["TRUE", "FALSE", "NOT GIVEN"],
    correct: 0,
    explanation: "The passage states that both subspecies of West Indian manatee are expected to undergo a decline of 20% over the next 40 years.",
  },
  {
    q: "The risk to manatees from entanglement and plastic consumption increased significantly in the period 2009-2020.",
    options: ["TRUE", "FALSE", "NOT GIVEN"],
    correct: 2,
    explanation: "A study cited 700 cases in that period, but the text does not state whether this represents an increase compared to previous years.",
  },
  {
    q: "There is some legislation in place which aims to reduce the likelihood of boat strikes on manatees in Florida.",
    options: ["TRUE", "FALSE", "NOT GIVEN"],
    correct: 0,
    explanation: "The text mentions that laws in certain parts of Florida now limit boat speeds during winter to help manatees respond.",
  },

  // Procrastination - Passage 2
  {
    q: "Which paragraph mentions false assumptions about why people procrastinate?",
    options: ["Paragraph A", "Paragraph B", "Paragraph C", "Paragraph D", "Paragraph E", "Paragraph F"],
    correct: 1,
    explanation: "Paragraph B states that 'Contrary to popular belief, procrastination is not due to laziness or poor time management.'",
  },
  {
    q: "Which paragraph references the realization that others also procrastinate?",
    options: ["Paragraph A", "Paragraph B", "Paragraph C", "Paragraph D", "Paragraph E", "Paragraph F"],
    correct: 5,
    explanation: "Paragraph F suggests reminding ourselves that 'we're not the first person to procrastinate, nor the last.'",
  },
  {
    q: "Which paragraph provides neurological evidence of a link between procrastination and emotion?",
    options: ["Paragraph A", "Paragraph B", "Paragraph C", "Paragraph D", "Paragraph E", "Paragraph F"],
    correct: 1,
    explanation: "Paragraph B mentions brain imaging research finding differences in brain areas linked to threat detection and emotion regulation in chronic procrastinators.",
  },
  {
    q: "Many people think that procrastination is the result of (17) __________.",
    options: ["laziness"],
    correct: 0,
    explanation: "Paragraph B identifies laziness as a common misconception for the cause of procrastination.",
  },
  {
    q: "The tasks we are most likely to put off are those that could damage our self-esteem or cause us to feel (18) __________ when we think about them.",
    options: ["anxious"],
    correct: 0,
    explanation: "The text states we put off tasks that threaten our self-worth or make us anxious.",
  },
  {
    q: "Research comparing chronic procrastinators with other people even found differences in the brain regions associated with regulating emotions and identifying (19) __________.",
    options: ["threats"],
    correct: 0,
    explanation: "Brain imaging studies linked procrastination to areas of the brain involved in detection of threats.",
  },
  {
    q: "Getting ready to take (20) __________ might be a typical example of an emotionally loaded or difficult task.",
    options: ["exams"],
    correct: 0,
    explanation: "The text specifically mentions preparing for exams as a prime candidate for procrastination.",
  },
  {
    q: "People who are likely to procrastinate tend to be either (21) __________ or those with low self-esteem.",
    options: ["perfectionists"],
    correct: 0,
    explanation: "Paragraph C identifies perfectionists and those with low self-esteem as groups prone to procrastination.",
  },
  {
    q: "Procrastination is often followed by a feeling of (22) __________ which worsens our mood.",
    options: ["guilt"],
    correct: 0,
    explanation: "The passage notes that after the temporary 'mood repair' of procrastination, people are often left with a sense of guilt.",
  },
  {
    q: "Which of the following is a comparison mentioned between employees who procrastinate and those who do not?",
    options: ["Their salaries are lower.", "The quality of their work is inferior.", "They have poorer relationships with colleagues.", "They enjoy their working lives more."],
    correct: 0,
    explanation: "A US survey mentioned in Paragraph D found that chronic procrastinators had less annual income.",
  },
  {
    q: "Which of the following is another comparison mentioned between employees who procrastinate and those who do not?",
    options: ["They have less employment stability.", "They are more likely to be promoted.", "They work longer hours.", "They have more job satisfaction."],
    correct: 0,
    explanation: "The same US survey in Paragraph D linked regular procrastination to less employment stability.",
  },
  {
    q: "Which is a recommendation for getting out of a cycle of procrastination?",
    options: ["not judging ourselves harshly", "setting ourselves manageable aims", "rewarding ourselves for tasks achieved", "prioritizing tasks by importance"],
    correct: 0,
    explanation: "Paragraph F recommends 'forgiving ourselves' and 'not being overly critical of ourselves' to break the cycle.",
  },
  {
    q: "Which is another recommendation for getting out of a cycle of procrastination?",
    options: ["avoiding things that stop us concentrating on our tasks", "taking more frequent breaks", "working in a public space", "asking others to monitor our progress"],
    correct: 0,
    explanation: "Paragraph F mentions evidence-based strategies to 'fend off distractions' that occupy our minds.",
  },

  // Robot Umpires - Passage 3
  {
    q: "When DeJesus first used ABS, he shared decision-making about strikes with it.",
    options: ["YES", "NO", "NOT GIVEN"],
    correct: 1,
    explanation: "The text states that DeJesus had decisions fed to him through an earpiece 'instead of making any judgments himself'.",
  },
  {
    q: "MLB considered it necessary to amend the size of the strike zone when criticisms were received from players.",
    options: ["YES", "NO", "NOT GIVEN"],
    correct: 0,
    explanation: "The passage says that in response to player complaints during the first season, 'MLB decided to tweak the dimensions of the zone'.",
  },
  {
    q: "MLB is keen to justify the money spent on improving the accuracy of ABS’s calculations.",
    options: ["YES", "NO", "NOT GIVEN"],
    correct: 2,
    explanation: "The text does not mention the cost of the system or MLB's need to justify the expenditure.",
  },
  {
    q: "The hundred-mile-an-hour fastball led to a more exciting style of play.",
    options: ["YES", "NO", "NOT GIVEN"],
    correct: 1,
    explanation: "The passage states the hundred-mile-an-hour fastball 'flattened the game into strikeouts, walks, and home runs—a type of play lacking much action.'",
  },
  {
    q: "The differing proposals for alterations to the baseball bat led to fierce debate on Sword’s team.",
    options: ["YES", "NO", "NOT GIVEN"],
    correct: 2,
    explanation: "While the team brainstormed potential fixes including changing the bats, there is no mention of a 'fierce debate'.",
  },
  {
    q: "ABS makes changes to the shape of the strike zone feasible.",
    options: ["YES", "NO", "NOT GIVEN"],
    correct: 0,
    explanation: "According to Morgan Sword, once the technology is right, you can 'load any strike zone you want into the system', even one shaped like Texas.",
  },
  {
    q: "MLB still wanted human umpires to shout out decisions as they had in their (33) __________.",
    options: ["A. pitch boundary", "B. numerous disputes", "C. team tactics", "D. subjective assessment", "E. widespread approval", "F. former roles", "G. total silence", "H. perceived area"],
    correct: 5,
    explanation: "MLB wanted human umpires to announce the calls 'just as they would have done in the past' (former roles).",
  },
  {
    q: "The umpire’s job had, at one time, required a (34) __________ about whether a ball was a strike.",
    options: ["A. pitch boundary", "B. numerous disputes", "C. team tactics", "D. subjective assessment", "E. widespread approval", "F. former roles", "G. total silence", "H. perceived area"],
    correct: 3,
    explanation: "Previously, calling a strike was a 'judgment call' or subjective assessment on the part of the umpire.",
  },
  {
    q: "A ball is considered a strike when it crosses through a (35) __________ extending from the batter’s knee to his chest.",
    options: ["A. pitch boundary", "B. numerous disputes", "C. team tactics", "D. subjective assessment", "E. widespread approval", "F. former roles", "G. total silence", "H. perceived area"],
    correct: 7,
    explanation: "The strike zone is described as an 'imaginary zone', which aligns with a 'perceived area'.",
  },
  {
    q: "In the past, (36) __________ over strike calls were not uncommon.",
    options: ["A. pitch boundary", "B. numerous disputes", "C. team tactics", "D. subjective assessment", "E. widespread approval", "F. former roles", "G. total silence", "H. perceived area"],
    correct: 1,
    explanation: "The text mentions 'countless arguments' and 'shouted disagreement' occurred for a hundred and fifty years.",
  },
  {
    q: "During the first game DeJesus used ABS, strike calls were met with (37) __________.",
    options: ["A. pitch boundary", "B. numerous disputes", "C. team tactics", "D. subjective assessment", "E. widespread approval", "F. former roles", "G. total silence", "H. perceived area"],
    correct: 6,
    explanation: "The text states that during the first game with ABS, 'there was no heckling and no shouted disagreement. Nobody said a word.'",
  },
  {
    q: "What does the writer suggest about ABS in the fifth paragraph?",
    options: [
      "It is bound to make key decisions that are wrong.",
      "It may reduce some of the appeal of the game.",
      "It will lead to the disappearance of human umpires.",
      "It may increase calls for the rules of baseball to be changed.",
    ],
    correct: 1,
    explanation: "The writer contrasts ABS with other sports technology, noting that in baseball, 'discretion has been appreciated' and implying the loss of that human element may reduce the game's appeal.",
  },
  {
    q: "Morgan Sword says that the introduction of ABS",
    options: [
      "was regarded as an experiment without a guaranteed outcome.",
      "was intended to keep up with developments in other sports.",
      "was a response to changing attitudes about the role of sport.",
      "was an attempt to ensure baseball retained a young audience.",
    ],
    correct: 3,
    explanation: "Sword explains that ABS was part of a project to make baseball more exciting because executives are 'terrified of losing younger fans'.",
  },
  {
    q: "Why does the writer include the views of Noë and Russo?",
    options: [
      "to show that attitudes to technology vary widely",
      "to argue that people have unrealistic expectations of sport",
      "to indicate that accuracy is not the same thing as enjoyment",
      "to suggest that the number of baseball fans needs to increase",
    ],
    correct: 2,
    explanation: "Noë and Russo both suggest that removing hard choices or making things 'perfect' through technology isn't necessarily desirable or real, highlighting that accuracy doesn't equal enjoyment.",
  },
];