export const questions = [
  {
    q: "Do you work or are you a student?",
    options: ["Open-ended response required."],
    correct: 0,
    explanation: "IELTS Speaking Part 1: Introduction and interview on familiar topics.",
  },
  {
    q: "What do you like most about your job/course?",
    options: ["Open-ended response required."],
    correct: 0,
    explanation: "IELTS Speaking Part 1: Focusing on personal background and preferences.",
  },
  {
    q: "What career would you like to have in the future?",
    options: ["Open-ended response required."],
    correct: 0,
    explanation: "IELTS Speaking Part 1: Discussing future aspirations.",
  },
  {
    q: "Is there anything you dislike about your studies/work?",
    options: ["Open-ended response required."],
    correct: 0,
    explanation: "IELTS Speaking Part 1: Balancing positive and negative feedback.",
  },
  {
    q: "What's your favorite fruit?",
    options: ["Open-ended response required."],
    correct: 0,
    explanation: "IELTS Speaking Part 1: Simple personal preference question.",
  },
  {
    q: "Are there any kinds of fruit that you don't like eating?",
    options: ["Open-ended response required."],
    correct: 0,
    explanation: "IELTS Speaking Part 1: Expressing dislikes.",
  },
  {
    q: "Do you like eating cooked food that has fruit in it?",
    options: ["Open-ended response required."],
    correct: 0,
    explanation: "IELTS Speaking Part 1: Specific detail on dietary preferences.",
  },
  {
    q: "Where's the best place to buy fruit where you live?",
    options: ["Open-ended response required."],
    correct: 0,
    explanation: "IELTS Speaking Part 1: Describing local environments.",
  },
  {
    q: "What do you enjoy doing in your free time?",
    options: ["Open-ended response required."],
    correct: 0,
    explanation: "IELTS Speaking Part 1: Discussion of leisure activities.",
  },
  {
    q: "Did you have any hobbies as a child?",
    options: ["Open-ended response required."],
    correct: 0,
    explanation: "IELTS Speaking Part 1: Recalling past experiences.",
  },
  {
    q: "Are there any hobbies you'd like to try in the future?",
    options: ["Open-ended response required."],
    correct: 0,
    explanation: "IELTS Speaking Part 1: Future intentions and interests.",
  },
  {
    q: "Do you prefer spending time alone or with friends?",
    options: ["Open-ended response required."],
    correct: 0,
    explanation: "IELTS Speaking Part 1: Social preferences and personality.",
  },
  {
    q: "Describe a time when you changed a plan you had made. You should say: •What your original plan was •Why you changed it •What new plan you made •And explain how you felt about changing your plan.",
    options: ["Open-ended long-form response (2 minutes)."],
    correct: 0,
    explanation: "IELTS Speaking Part 2: The Individual Long Turn/Cue Card.",
  },
  {
    q: "What kinds of plans do friends make together?",
    options: ["Analytical discussion response required."],
    correct: 0,
    explanation: "IELTS Speaking Part 3: Two-way discussion on abstract social concepts.",
  },
  {
    q: "Do you think it's better to discuss future plans with friends or with family?",
    options: ["Analytical discussion response required."],
    correct: 0,
    explanation: "IELTS Speaking Part 3: Comparing different viewpoints.",
  },
  {
    q: "When making plans for the future, is it important not to copy friends?",
    options: ["Analytical discussion response required."],
    correct: 0,
    explanation: "IELTS Speaking Part 3: Evaluating personal independence and influence.",
  },
  {
    q: "When people are choosing what to study, how important is it that their course should lead directly to a career?",
    options: ["Analytical discussion response required."],
    correct: 0,
    explanation: "IELTS Speaking Part 3: Discussing education and employment connections.",
  },
  {
    q: "Why is it a good idea to get some work experience before deciding on a future career?",
    options: ["Analytical discussion response required."],
    correct: 0,
    explanation: "IELTS Speaking Part 3: Reasoning through professional development choices.",
  },
  {
    q: "How easy do you think it is for people to change from one career to another?",
    options: ["Analytical discussion response required."],
    correct: 0,
    explanation: "IELTS Speaking Part 3: Analyzing societal and professional mobility.",
  },
];