// Script/examManifest.js
// Auto-generated by ./tools/generateExamManifest.js - do not edit by hand
// Run: node tools/generateExamManifest.js
// Last generated at: 2026/2/9   |   9:31 PM

export const examList = [
  {
    "id": "22PA7FMJ",
    "title": "Listining",
    "path": "../Exams/English Student [PH]/1/1/Academic IELTS Test Format/Listining.js",
    "category": "Academic IELTS Test Format"
  },
  {
    "id": "CAENTK6V",
    "title": "Reading",
    "path": "../Exams/English Student [PH]/1/1/Academic IELTS Test Format/Reading.js",
    "category": "Academic IELTS Test Format"
  },
  {
    "id": "PCPYIF7O",
    "title": "Speaking",
    "path": "../Exams/English Student [PH]/1/1/Academic IELTS Test Format/Speaking.js",
    "category": "Academic IELTS Test Format"
  },
  {
    "id": "QIYGG3Z7",
    "title": "Writing",
    "path": "../Exams/English Student [PH]/1/1/Academic IELTS Test Format/Writing.js",
    "category": "Academic IELTS Test Format"
  },
  {
    "id": "2ZF6YJ4J",
    "title": "WEATHER AND HEALTH",
    "path": "../Exams/English Student [PH]/1/1/English/WEATHER AND HEALTH.js",
    "category": "English"
  },
  {
    "id": "EGJZO3ZX",
    "title": "TECHNOLOGY",
    "path": "../Exams/English Student [PH]/1/1/English/TECHNOLOGY.js",
    "category": "English"
  },
  {
    "id": "G7QUMCKU",
    "title": "DIET AND HEALTH",
    "path": "../Exams/English Student [PH]/1/1/English/DIET AND HEALTH.js",
    "category": "English"
  },
  {
    "id": "HGT44EQE",
    "title": "SHARED LIVING",
    "path": "../Exams/English Student [PH]/1/1/English/SHARED LIVING.js",
    "category": "English"
  },
  {
    "id": "HQHGSQ4H",
    "title": "PROFESSIONAL LIFE",
    "path": "../Exams/English Student [PH]/1/1/English/PROFESSIONAL LIFE.js",
    "category": "English"
  },
  {
    "id": "YRAA2R57",
    "title": "Reading Exam",
    "path": "../Exams/English Student [PH]/1/1/Reading/Reading Exam.js",
    "category": "Reading"
  }
];

export const categoryTree = {
  "Academic IELTS Test Format": {
    "id": "Y3ZL4SML",
    "name": "Academic IELTS Test Format",
    "faculty": "English Student [PH]",
    "year": "1",
    "term": "1",
    "path": [
      "Academic IELTS Test Format"
    ],
    "parent": null,
    "subcategories": [],
    "exams": [
      {
        "id": "22PA7FMJ",
        "title": "Listining",
        "path": "../Exams/English Student [PH]/1/1/Academic IELTS Test Format/Listining.js",
        "category": "Academic IELTS Test Format"
      },
      {
        "id": "CAENTK6V",
        "title": "Reading",
        "path": "../Exams/English Student [PH]/1/1/Academic IELTS Test Format/Reading.js",
        "category": "Academic IELTS Test Format"
      },
      {
        "id": "PCPYIF7O",
        "title": "Speaking",
        "path": "../Exams/English Student [PH]/1/1/Academic IELTS Test Format/Speaking.js",
        "category": "Academic IELTS Test Format"
      },
      {
        "id": "QIYGG3Z7",
        "title": "Writing",
        "path": "../Exams/English Student [PH]/1/1/Academic IELTS Test Format/Writing.js",
        "category": "Academic IELTS Test Format"
      }
    ]
  },
  "English": {
    "id": "AD6EJ4DM",
    "name": "English",
    "faculty": "English Student [PH]",
    "year": "1",
    "term": "1",
    "path": [
      "English"
    ],
    "parent": null,
    "subcategories": [],
    "exams": [
      {
        "id": "G7QUMCKU",
        "title": "DIET AND HEALTH",
        "path": "../Exams/English Student [PH]/1/1/English/DIET AND HEALTH.js",
        "category": "English"
      },
      {
        "id": "HQHGSQ4H",
        "title": "PROFESSIONAL LIFE",
        "path": "../Exams/English Student [PH]/1/1/English/PROFESSIONAL LIFE.js",
        "category": "English"
      },
      {
        "id": "HGT44EQE",
        "title": "SHARED LIVING",
        "path": "../Exams/English Student [PH]/1/1/English/SHARED LIVING.js",
        "category": "English"
      },
      {
        "id": "EGJZO3ZX",
        "title": "TECHNOLOGY",
        "path": "../Exams/English Student [PH]/1/1/English/TECHNOLOGY.js",
        "category": "English"
      },
      {
        "id": "2ZF6YJ4J",
        "title": "WEATHER AND HEALTH",
        "path": "../Exams/English Student [PH]/1/1/English/WEATHER AND HEALTH.js",
        "category": "English"
      }
    ]
  },
  "Reading": {
    "id": "REXXQROQ",
    "name": "Reading",
    "faculty": "English Student [PH]",
    "year": "1",
    "term": "1",
    "path": [
      "Reading"
    ],
    "parent": null,
    "subcategories": [],
    "exams": [
      {
        "id": "YRAA2R57",
        "title": "Reading Exam",
        "path": "../Exams/English Student [PH]/1/1/Reading/Reading Exam.js",
        "category": "Reading"
      }
    ]
  }
};
